# mkdocs.yml
site_name: EduManage - Documentación Técnica
site_description: Sistema integral de gestión educativa
site_author: Matías Pérez 
site_url: https://matipebu.github.io/despr1_4_mkdocs/

# Repositorio
repo_name: matipebu/despr1_4_mkdocs
repo_url: https://github.com/matipebu/despr1_4_mkdocs
edit_uri: edit/main/docs/

theme:
  name: material
  language: es
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - content.code.annotate
    - content.code.copy


# Plugins
plugins:
  - search:
      lang: es
  - mermaid2:
      arguments:
        theme: base

# Extensiones Markdown
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
  - md_in_html
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - mdx_math:
      enable_dollar_delimiter: True
  - pymdownx.tasklist:
      custom_checkbox: true

# Navegación
nav:
  - Inicio: index.md
  - Instalación: instalacion.md
  - Autenticación: 
    - Sistema de Login: ./modulos/login.md
    - Configuración OAuth: ./modulos/oauth.md
  - Dashboard:
    - Vista General: ./modulos/dashboard.md
    - Métricas: ./modulos/metricas.md
  - Configuración: ./modulos/settings.md

# Configuración adicional
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/matipebu
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/matipebu

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
